# Generated by Django 4.1 on 2023-12-17 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionoption',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('C', 'Classic question'), ('B', 'Yes/No question'), ('m', 'Multiple options question'), ('I', 'Image question'), ('S', 'Score question')], default='C', max_length=1),
        ),
    ]
