# Generated by Django 4.1 on 2023-11-27 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0005_question_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('C', 'Classic question'), ('B', 'Yes/No question'), ('S', 'Score question')], default='C', max_length=1),
        ),
    ]
