# Generated by Selenium IDE
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from selenium.common.exceptions import WebDriverException

from django.contrib.staticfiles.testing import StaticLiveServerTestCase
from base.tests import BaseTestCase

import time
import os

class TestSelenium(StaticLiveServerTestCase):
  def setUp(self):
    # Configuración específica para Selenium y WebDriver
    options = webdriver.ChromeOptions()
    options.headless = False 
    self.driver = webdriver.Chrome(options=options)

    super().setUp()

    # Configuración específica para Django y el cliente de prueba
    self.base = BaseTestCase()
    self.vars = {}
    self.base.setUp()    
       
          
  def tearDown(self):           
    super().tearDown()
    self.driver.quit()

    self.base.tearDown()
  
  def test_CorrectImport(self):
    self.driver.get("http://localhost:8000/admin/census/census")
    self.driver.set_window_size(1210, 773)
    self.driver.find_element(By.ID, "id_username").click()
    self.driver.find_element(By.ID, "id_username").send_keys("admin")
    self.driver.find_element(By.ID, "id_password").send_keys("admin")
    self.driver.find_element(By.ID, "id_password").send_keys(Keys.ENTER)
    self.driver.find_element(By.LINK_TEXT, "Censuss").click()
    self.driver.find_element(By.CSS_SELECTOR, ".import_link").click()

    DIR = os.path.dirname(os.path.realpath(__file__))
    archivo_relativo = 'static/censoTestImport.xlsx'
    archivo_absoluto = os.path.join(DIR, archivo_relativo)

    try:
      file_input = self.driver.find_element(By.ID, "id_import_file")
      file_input.send_keys(archivo_absoluto)
      time.sleep(3)
    except WebDriverException as e:
      print(f"Error al enviar teclas al elemento: {e}")

    dropdown = self.driver.find_element(By.ID, "id_input_format")
    dropdown.find_element(By.XPATH, "//option[. = 'xlsx']").click()
    self.driver.find_element(By.CSS_SELECTOR, ".default").click()    
    time.sleep(3)
    self.driver.find_element(By.NAME, "confirm").click()
    time.sleep(3)
    self.driver.find_element(By.CSS_SELECTOR, ".export_link").click()
    self.driver.find_element(By.ID, "id_file_format").click()
    dropdown = self.driver.find_element(By.ID, "id_file_format")
    dropdown.find_element(By.XPATH, "//option[. = 'xlsx']").click()
    self.driver.find_element(By.CSS_SELECTOR, ".default").click()

